Mappings:
  RegionMap:
    us-east-1:
      HVM64: ami-0b69ea66ff7391e80
    us-east-2:
      HVM64: ami-00c03f7f7f2ec15c3
    us-west-1:
      HVM64: ami-0245d318c6788de52
    us-west-2:
      HVM64: ami-04b762b4289fba92b
    ap-south-1:
      HVM64: ami-0cb0e70f44e1a4bb5
    ap-northeast-2:
      HVM64: ami-0d097db2fb6e0f05e
    ap-southeast-1:
      HVM64: ami-048a01c78f7bae4aa
    ap-southeast-2:
      HVM64: ami-03ed5bd63ba378bd8
    ap-northeast-1:
      HVM64: ami-0ff21806645c5e492
    ca-central-1:
      HVM64: ami-085edf38cedbea498
    eu-central-1:
      HVM64: ami-00aa4671cbf840d82
    eu-west-1:
      HVM64: ami-0ce71448843cb18a1
    eu-west-2:
      HVM64: ami-00a1270ce1e007c27
    eu-west-3:
      HVM64: ami-03b4b78aae82b30f1
    eu-north-1:
      HVM64: ami-1b2fa465
    sa-east-1:
      HVM64: ami-0a1f49a762473adbd

Resources:
  WebApp:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: "MicroWeb"

Outputs:
  WebApp:
    Description : Public Ip Address
    Value: !GetAtt WebApp.PublicIp